
package com.business_post.ukmail.mailmark.manifest;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import com.ukmail.ns.msg.header._1.Header;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "mailmark.onramp.portType", targetNamespace = "http://ukmail.business-post.com/mailmark/manifest")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.business_post.ukmail.mailmark.manifest.ObjectFactory.class,
    com.ukmail.ns.msg.fault._1.ObjectFactory.class,
    com.ukmail.ns.msg.header._1.ObjectFactory.class
})
public interface MailmarkOnrampPortType {


    /**
     * 
     * @param itemManifest1Request
     * @param header
     * @return
     *     returns java.lang.String
     * @throws Fault
     */
    @WebMethod(operationName = "item_manifest-1", action = "http://ukmail.business-post.com/mailmark/manifest")
    @WebResult(name = "status", targetNamespace = "http://ukmail.business-post.com/mailmark/manifest", partName = "item_manifest-1.response")
    public String itemManifest1(
        @WebParam(name = "ItemsBatch", targetNamespace = "http://ukmail.business-post.com/mailmark/manifest", partName = "item_manifest-1.request")
        ItemsBatch itemManifest1Request,
        @WebParam(name = "ukmail", targetNamespace = "http://ns.ukmail.com/msg/header/1.0", header = true, mode = WebParam.Mode.INOUT, partName = "header")
        Holder<Header> header)
        throws Fault
    ;

}
